---
name: "tagged-release"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  tagged-release:
    permissions:
      contents: write
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: zip  
        uses: vimtor/action-zip@v1
        with:
          files: pydfmerger.py README.md requirements.txt LICENSE
          dest: "${{ github.workspace }}/${{github.ref_name}}.zip"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            "${{ github.workspace }}/${{github.ref_name}}.zip"
