---
name: "tagged-release"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  tagged-release:
    permissions:
      contents: write
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: zip  
        uses: vimtor/action-zip@v1
        with:
          files: pydfmerger.py README.md requirements.txt LICENSE
          dest: "${{ github.workspace }}/${{github.ref_name}}.zip"
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "${{ github.workspace }}/${{github.ref_name}}.zip"
          asset_name: ${{github.ref_name}}.zip
          asset_content_type: application/zip
